# Generated by Django 5.1.15 on 2026-01-03 16:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('work_mode', models.CharField(choices=[('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('ONSITE', 'Onsite'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('RSS', 'RSS'), ('EMAIL', 'Email Alert'), ('WHITELIST', 'Whitelisted Browse')], default='MANUAL', max_length=20)),
                ('job_url', models.URLField(blank=True, max_length=500)),
                ('jd_text', models.TextField(blank=True)),
                ('is_scam_suspected', models.BooleanField(default=False)),
                ('scam_reasons', models.TextField(blank=True)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DISCOVERED', 'Discovered'), ('SHORTLISTED', 'Shortlisted'), ('APPLIED', 'Applied'), ('OA_TEST', 'OA / Test'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('REJECTED', 'Rejected'), ('GHOSTED', 'Ghosted')], default='DISCOVERED', max_length=20)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tracker.joblead')),
            ],
        ),
    ]
