# Generated by Django 5.1.15 on 2026-01-06 05:46

from django.conf import settings
from django.db import migrations, models


def dedupe_applications(apps, schema_editor):
    Application = apps.get_model("tracker", "Application")
    duplicates = (
        Application.objects.values("job_id", "owner_id")
        .annotate(count=models.Count("id"))
        .filter(count__gt=1)
    )
    for dup in duplicates:
        ids = list(
            Application.objects.filter(job_id=dup["job_id"], owner_id=dup["owner_id"])
            .order_by("id")
            .values_list("id", flat=True)
        )
        for app_id in ids[1:]:
            Application.objects.filter(pk=app_id).delete()


def backfill_joblead_owners(apps, schema_editor):
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(user_app_label, user_model_name)
    JobLead = apps.get_model("tracker", "JobLead")
    Application = apps.get_model("tracker", "Application")

    fallback_user = User.objects.filter(is_superuser=True).order_by("id").first()
    if fallback_user is None:
        fallback_user = User.objects.order_by("id").first()
    fallback_user_id = fallback_user.id if fallback_user else None

    if JobLead.objects.filter(owner_id__isnull=True).exists() and fallback_user_id is None:
        raise RuntimeError("Job leads without owners found but no users exist to assign.")

    for lead in JobLead.objects.filter(owner_id__isnull=True):
        owner_id = (
            Application.objects.filter(job_id=lead.id)
            .order_by("id")
            .values_list("owner_id", flat=True)
            .first()
        )
        if owner_id is None:
            owner_id = fallback_user_id
        if owner_id:
            JobLead.objects.filter(pk=lead.pk).update(owner_id=owner_id)


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_userprofile_settings_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='joblead',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblead',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joblead',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(dedupe_applications, migrations.RunPython.noop),
        migrations.RunPython(backfill_joblead_owners, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('job', 'owner'), name='unique_application_per_owner_job'),
        ),
    ]
